questions = [
    ['Category', 'Question 1?', 'Answer'],
    ['Category', 'Question 2?', 'Answer'],
    ['Category', 'Question 3?', 'Answer'],
    ['Category', 'Question 4?', 'Answer'],
    ['Category', 'Question 5?', 'Answer'],
    ['Category', 'Question 6?', 'Answer'],
    ['Category', 'Question 7?', 'Answer'],
    ['Category', 'Question 8?', 'Answer'],
    ['Category', 'Question 9?', 'Answer'],
    ['Category', 'Question 10?', 'Answer'],
    ['Category', 'Question 11?', 'Answer'],
    ['Category', 'Question 12?', 'Answer'],
    ['Category', 'Question 13?', 'Answer'],
    ['Category', 'Question 14?', 'Answer'],
    ['Category', 'Question 15?', 'Answer'],
    ['Category', 'Question 16?', 'Answer'],
    ['Category', 'Question 17?', 'Answer'],
    ['Category', 'Question 18?', 'Answer'],
    ['Category', 'Question 19?', 'Answer'],
    ['Category', 'Question 20?', 'Answer']
]
